### ISSUE TITLE
`LICENSE.md` for repository

### ISSUE THREAD

**Issue by mrghosti3** [codytrey/gen_gcode#1]
Would you be willing to add `LICENSE.md` file to repository with license contents that are mentioned `Cargo.toml`?

https://github.com/codytrey/gen_gcode/blob/ac1c336b532cd0ca95e1f05e1e2934dd5f520fcc/Cargo.toml#L6

P.S. are you accepting merges?

**Comment by codytrey** [comment]
I haven't touched this code in a long time. But if you think it may be useful to anyone, feel free to submit a merge request and I'll review it.
